### ISSUE TITLE
Error on opening flutter project in Inteiij Idea 

### ISSUE THREAD

**Issue by rishabhdeepsingh** [georgeherby/flutter-snippets#14]
```prolog
com.intellij.diagnostic.PluginException: Cannot create extension (class=FlutterContext) [Plugin: com.gionchat]
	at com.intellij.serviceContainer.ComponentManagerImpl.createError(ComponentManagerImpl.kt:932)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.createInstance(XmlExtensionAdapter.java:88)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapter(ExtensionPointImpl.java:486)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapters(ExtensionPointImpl.java:434)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.calcExtensionList(ExtensionPointImpl.java:241)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.getExtensionList(ExtensionPointImpl.java:235)
	at com.intellij.codeInsight.template.impl.TemplateContextTypes.getAllContextTypes(TemplateContextTypes.java:20)
	at com.intellij.codeInsight.template.impl.TemplateContext$1.compute(TemplateContext.java:51)
	at com.intellij.codeInsight.template.impl.TemplateContext$1.compute(TemplateContext.java:31)
	at com.intellij.openapi.util.ClearableLazyValue.getValue(ClearableLazyValue.java:39)
	at com.intellij.codeInsight.template.impl.TemplateContext.readTemplateContext(TemplateContext.java:105)
	at com.intellij.codeInsight.template.impl.TemplateSettings.readTemplateFromElement(TemplateSettings.java:713)
	at com.intellij.codeInsight.template.impl.TemplateSettings.parseTemplateGroup(TemplateSettings.java:614)
	at com.intellij.codeInsight.template.impl.TemplateSettings$1.readScheme(TemplateSettings.java:199)
	at com.intellij.codeInsight.template.impl.TemplateSettings$1.readScheme(TemplateSettings.java:195)
	at com.intellij.configurationStore.schemeManager.SchemeLoader.loadScheme(schemeLoader.kt:187)
	at com.intellij.configurationStore.schemeManager.SchemeManagerImpl$loadSchemes$isLoadOnlyFromProvider$2.invoke(SchemeManagerImpl.kt:214)
	at com.intellij.configurationStore.schemeManager.SchemeManagerImpl$loadSchemes$isLoadOnlyFromProvider$2.invoke(SchemeManagerImpl.kt:42)
	at com.intellij.cloudConfig.CloudConfigStreamProvider.processChildren(CloudConfigStreamProvider.kt:92)
	at com.intellij.configurationStore.CompoundStreamProvider.processChildren(CompoundStreamProvider.kt:28)
	at com.intellij.configurationStore.schemeManager.SchemeManagerImpl.loadSchemes(SchemeManagerImpl.kt:212)
	at com.intellij.codeInsight.template.impl.TemplateSettings.<init>(TemplateSettings.java:278)
	at com.intellij.codeInsight.template.impl.TemplateSettings.<init>(TemplateSettings.java:190)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:47)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:877)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:48)
	at com.intellij.serviceContainer.ServiceComponentAdapter.access$createAndInitialize(ServiceComponentAdapter.kt:12)
	at com.intellij.serviceContainer.ServiceComponentAdapter$doCreateInstance$1.run(ServiceComponentAdapter.kt:42)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:223)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:41)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:113)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:67)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:60)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:590)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:573)
	at com.intellij.openapi.client.ClientAwareComponentManager.getFromSelfOrCurrentSession(ClientAwareComponentManager.kt:37)
	at com.intellij.openapi.client.ClientAwareComponentManager.getService(ClientAwareComponentManager.kt:22)
	at com.intellij.codeInsight.template.impl.TemplateSettings.getInstance(TemplateSettings.java:302)
	at com.intellij.codeInsight.template.impl.LiveTemplatesOptionsTopHitProvider.getOptions(LiveTemplatesOptionsTopHitProvider.java:24)
	at com.intellij.ide.ui.TopHitCache.lambda$getCachedOptions$0(TopHitCache.java:66)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1737)
	at com.intellij.ide.ui.TopHitCache.getCachedOptions(TopHitCache.java:58)
	at com.intellij.ide.ui.OptionsTopHitProvider.getCachedOptions(OptionsTopHitProvider.java:53)
	at com.intellij.ide.ui.OptionsTopHitProvider$Activity.lambda$cacheAll$1(OptionsTopHitProvider.java:200)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processWithPluginDescriptor(ExtensionPointImpl.java:293)
	at com.intellij.openapi.extensions.ExtensionPointName.processWithPluginDescriptor(ExtensionPointName.java:156)
	at com.intellij.ide.ui.OptionsTopHitProvider$Activity.cacheAll(OptionsTopHitProvider.java:196)
	at com.intellij.ide.ui.OptionsTopHitProvider$Activity.preload(OptionsTopHitProvider.java:177)
	at com.intellij.idea.ApplicationLoader$executePreloadActivity$1.run(ApplicationLoader.kt:412)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.idea.ApplicationLoader.executePreloadActivity(ApplicationLoader.kt:402)
	at com.intellij.idea.ApplicationLoader.access$executePreloadActivity(ApplicationLoader.kt:1)
	at com.intellij.idea.ApplicationLoader$executePreloadActivities$2.run(ApplicationLoader.kt:467)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.ClassNotFoundException: FlutterContext PluginClassLoader(plugin=PluginDescriptor(name=Flutter Snippets, id=com.gionchat, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/212.4746.52/IntelliJ IDEA 2021.2 EAP.app.plugins/FlutterSnippets.jar, version=1.3.4, package=null), packagePrefix=null, instanceId=13, state=active)
	at com.intellij.serviceContainer.ComponentManagerImplKt.doLoadClass(ComponentManagerImpl.kt:1489)
	at com.intellij.serviceContainer.ComponentManagerImplKt.access$doLoadClass(ComponentManagerImpl.kt:1)
	at com.intellij.serviceContainer.ComponentManagerImpl.loadClass(ComponentManagerImpl.kt:821)
	at com.intellij.openapi.extensions.impl.InterfaceExtensionImplementationClassResolver.resolveImplementationClass(InterfaceExtensionImplementationClassResolver.java:25)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.createInstance(XmlExtensionAdapter.java:65)
	... 66 more
```

**Comment by georgeherby** [comment]
Hey -  are you using the plugin from the marketplace if so which version and intellij version? As I am for used why the plugin I'd is `com.gionchat`

Do you have the flutter plugin installed, if so which version?

**Comment by rishabhdeepsingh** [comment]
```
IntelliJ IDEA 2021.2 RC (Ultimate Edition)
Build #IU-212.4746.52, built on July 20, 2021
Licensed to RISHABHDEEP SINGH
Subscription is active until April 13, 2022.
For educational use only.
Runtime version: 11.0.11+9-b1504.13 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.5
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 16
Registry: ide.mac.transparentTitleBarAppearance=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: Batch Scripts Support (1.0.12), CMD Support (1.0.5), com.gionchat (1.3.4), net.seesharpsoft.intellij.plugins.csv (2.17.1), com.mallowigi (38.0.0), some.awesome (1.14), CHelper (4.4.2), EclipseCodeFormatter (20.8.203.000.0-Eclipse_2020-06-JavaOnly), com.github.setial (4.0.2), com.herbert.george.flutter-snippets (2.0.0-stable-1), Dart (212.4746.57), io.flutter (58.0.4), Pythonid (212.4746.64), com.chrisrm.idea.MaterialThemeUI (6.7.2-2021.2), izhangzhihao.rainbow.brackets (6.19), ru.adelf.idea.dotenv (2021.2.212)
Kotlin: 212-1.5.10-release-IJ4746.52
```

**Comment by georgeherby** [comment]
Hi @rishabhdeepsingh and you are running my version of Flutter snippets that you downloaded from the marketplace in intellij?

As this line suggest you are not and running using what I guess is a forked version 

```Caused by: java.lang.ClassNotFoundException: FlutterContext PluginClassLoader(plugin=PluginDescriptor(name=Flutter Snippets, id=com.gionchat, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/212.4746.52/IntelliJ IDEA 2021.2 EAP.app.plugins/FlutterSnippets.jar, version=1.3.4, package=null), packagePrefix=null, instanceId=13, state=active)``` 

which I can see does exist on the gionchat github user.

**Comment by zakblacki** [comment]
Same issue until now 

![image](https://user-images.githubusercontent.com/29728429/170861908-c14bd244-84dc-456e-8181-877057f89594.png)

![image](https://user-images.githubusercontent.com/29728429/170861913-67bff299-8cc9-4187-84df-c113cd3039b9.png)

**Comment by georgeherby** [comment]
I have just created a fresh install of Android Studio, ensured I installed Flutter plugin, Dart Plugin and then the FLutter Snippets (there is a new version from the one you tried `2.1.0-stable-1` and it worked fine. Please ensure you have all the plugins installed and on the latest version. 

![image](https://user-images.githubusercontent.com/21989833/172069915-eb2dd514-d815-4b12-8cfa-333c36964d43.png)

As this cannot be replicated I am going to close the issue feel free to reopen if you have more details or steps
